# Servidor HTTP - solo para Let's Encrypt y redirección
server {
    listen 80;
    server_name backend.hopta.hn;

    # Carpeta para desafíos de Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirección a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# Servidor HTTPS - con SSL
server {
    listen 443 ssl;
    server_name backend.hopta.hn;

    ssl_certificate /etc/letsencrypt/live/backend.hopta.hn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/backend.hopta.hn/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host $host;

        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        chunked_transfer_encoding off;
    }
}
